# .travis.yml
language: go
go:
  - 1.8.x
  - tip
before_install:
  - go get -t -v ./...
  - go get github.com/haya14busa/goverage

script:
  - goverage -coverprofile=coverage.txt ./...

after_success:
  - goveralls -service=travis-ci -coverprofile=coverage.txt
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
